spring.datasource.url=jdbc:postgresql://ep-damp-heart-b6cmygiz.c-2.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_S4iHz2qlKYgh

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect